on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar variáveis de ambiente
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV

      - name: Rodar deploy
        run: |
          echo "Usando secret: $SECRET_KEY"
          ./deploy.sh  # ou o comando que você usa
